### ISSUE TITLE
Sử dụng Docker và Docker Compose để deploy code

### ISSUE THREAD

**Issue by Riiichan04** [NguyenLoan04/WebTranhTheu_LTWEB_NLU_NHOM26#132]
## Giới thiệu
- Để có thể kết nối vào máy ảo Linux. Ta cần tạo 1 kết nối SSH từ máy thật đến máy ảo và sẽ thao tác thông qua các phần mềm chuyên dụng như `Putty` hay `MobaXterm` hoặc cmd (và cài đặt thêm các thư viện và phần mềm hỗ trợ). (Xem #128)

- Quá trình deploy được diễn ra theo các bước sau:
1. Upload các file cần thiết lên máy ảo bằng SSH
2. Dùng Docker để chạy mysql, tạo các bảng và đổ dữ liệu vào database trên máy ảo
3. Dùng Docker để tiến hành build và chạy code

- Có thể thấy, đó là quy trình mặc định được đề cập trong #135. Tuy nhiên, trong thực tế, khi số lượng container không chỉ dừng lại ở con số 2, mà lên đến hàng trăm, hàng nghìn thì ta có thể sử dụng một công cụ hỗ trợ tên là ***Docker Compose*** để giải quyết vấn đề trên. Issue này sẽ đề cập đến việc sử dụng **Docker Compose** để tiến hành deploy và chạy ứng dụng web.

### 1. Các file cần thêm vào để tiến hành deploy
Quá trình deploy cần phải cho thêm một số file vào root của project. Do khi sử dụng **Docker Compose**, ta sẽ upload src code lên máy ảo lẫn **Dockerfile** để tiến hành build container webapp.
- ***.env***: Dùng để chứa các biến môi trường dùng cho `docker-compose.yml`. Trong repo này, nội dung của `.env` gồm:
```env
MYSQL_DBNAME=Tên_database
MYSQL_PASSWORD=Mật_khẩu_root_của_mysql
``` 
   Với `MYSQL_PASSWORD`, đây là password dùng cho tài khoản root của container MySQL. Có thể đặt password này tùy ý thích.

- Các file ***.properties***: Dùng để khai báo các biến để sử dụng các api hay service khác. Các file cần thay đổi như sau:

`db.properties`. Để có thể chạy trên máy ảo thì nội dung của file gồm:
```properties
db.host=mysql  #Đây là tên host mặc định dùng để kết nối đến image `mysql` trong Docker
db.port=3306  #Đây là port mặc định của MySQL
db.username=root  #Sẽ đăng nhập bằng user root
db.password=mật_khẩu_cho_root #Mật khẩu của root. Cần phải giống với MYSQL_PASSWORD trong .env
db.name=tên_database #Tên database. Cần phải giống với MYSQL_DBNAME trong .env
db.options=useUnicode=true&characterEncoding=UTF-8 #Option có thể chọn tùy ý thích
```

`vm.properties`: Cần thêm file này để cấu hình cho `org.hidetake.ssh`:
```properties
host=host_của_máy_ảo
user=username_của_máy_ảo
password=password_của_máy_ảo
```

### 2. Cấu hình `Dockerfile` dành cho deploy code
Các bước Dockerfile thực hiện:
- Lấy image `Gradle`
- Copy các file cần thiết vào bên trong Docker: `src`, các file `.gradle.kts`.
- Tiến hành build bằng `gradle war`
- Lấy image `Tomcat 10`
- Copy file .`war` vào `/usr/local/tomcat/webapps/ROOT.war`. Dùng `ROOT.war` để khi deploy thì khi chạy chỉ cần mở `url/`.
- Tiến hành chạy `catalina.sh` để chạy Tomcat.

Cụ thể xem ở [`Dockerfile`](https://github.com/NguyenLoan04/WebTranhTheu_LTWEB_NLU_NHOM26/blob/master/Dockerfile)
### 3. Cấu hình `docker-compose.yml`
Cấu hình ***docker-compose*** của project này như sau:
```yml
services:
    web: #Tên Service (khác tên Container)
        build: #Thông tin khi build
            context: . #Thư mục chứa Dockerfile
            dockerfile: Dockerfile #Khai báo Dockerfile (Trong trường hợp có tên khác)
        container_name: tomcat10 #Tên container
        depends_on: #Cần chạy container mysql trước
            -   mysql
        ports: #Map port trong nội bộ docker với cổng bên ngoài (máy ảo)
            - "80:8080"
        restart: always #Nếu có lỗi thì tự restart

    mysql: #Tên Service
        image: mysql:latest #Image sử dụng
        container_name: mysql #Tên container
        ports:
            - "3306:3306"
        restart: always
        environment: #Khai báo các biến môi trường cần thiết
            MYSQL_DATABASE: ${MYSQL_DBNAME} #Docker compose tự động đọc file .env trong cùng cấp và truyền vào
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes: #Tạo các volume
            - mysql_data:/var/lib/mysql #Volume chứa data của mysql, nếu không có thì khi container mysql restart sẽ mất hết dữ liệu

volumes: #Khai báo tên các volume
    mysql_data:
```

## Thực hiện
- [x] Các thành viên trong nhóm đều có thể deploy project lên máy ảo được
